.github/workflows/ci.yml, README.md
- Link the design guide in README
- Fix CI to allow external pull request
=> Small fix for open source

src/Float.mo, test/floatTest.mo
=> Add formatting for Float.mo

src/Array.mo, test/arrayTest.mo
=> Adds filterMap for arrays

README.md
=> Readme: Fix vessel instructions

src/List.mo
Also deletes an unused internal function
=> Cleans up a few comments in List

src/Word16.mo, src/Word32.mo, src/Word64.mo, src/Word8.mo
see https://github.com/dfinity-lab/motoko/pull/1709
=> Remove WordN.toInt

src/Word16.mo, src/Word32.mo, src/Word64.mo, src/Word8.mo
This reverts commit d0354489313e7334054505abe04574482d409cbd.
=> Revert "Remove WordN.toInt (#125)" and reimplement

.github/workflows/ci.yml, src/AssocList.mo, src/Trie.mo, src/TrieMap.mo, src/TrieSet.mo, src/Word16.mo, src/Word32.mo, src/Word64.mo, src/Word8.mo
This is in preparation for me bumping master to dfx 0.5.13
=> Updates next-moc with latest master changes

src/TrieSet.mo, test/trieSetTest.mo
Some utility functions for sets.
Also, should `mem` be renamed to `has`?
=> Add TrieSet functions to convert to/from arrays

src/Array.mo, test/arrayTest.mo
- Documents all functions
- Revises `len` ~> `size`, for style compliance
=> Documentation for Array module

.github/workflows/ci.yml, doc/README.md, doc/make_data_uri.sh, doc/module_graph.py
Think this is a useful addition?
If so, do we want to run this on CI to make sure it passes?
If so, do we want CI to put the generated image somewhere?
=> Adds a script to visualize module dependencies

src/Option.mo
=> Fixes syntax errors in Option module docs

src/Time.mo
Many thanks to Claudio for providing an example for me to include in the dfx doc and here.
I think this is the kind of thing the community has been asking for more of ...
=> Add a simple example to the Time.mo source

doc/modules/base-libraries/pages/stdlib-intro.adoc
Just a quick draft. Feel free to pick on it and submit improvements.
=> Remove section about Prelude

src/ExperimentalFunds.mo
Not clear I can test this here since it requires some implementation of the platform. @kritzcreek?
=> Adds an experimental funds library

.github/workflows/ci.yml
following advise from https://github.com/cachix/install-nix-action/issues/59#issuecomment-731063013
=> Refine CI: Do not use `nix-channel`

src/ExperimentalCycles.mo
Might be worth reviewing early, in the hope that we can ship with the next release
=> ExperimentalCycles lib

doc/modules/base-libraries/pages/stdlib-intro.adoc
Remove obsolete stuff, add pointer to the repo directly. add how to search for doc.
=> Update intro page for base

doc/modules/base-libraries/pages/stdlib-intro.adoc
Fix content in master for the doc-pages branch.
=> Add info about local documentation and remove the nowhere link

src/Text.mo, test/textTest.mo
including mild documentation and tests.
=> Add Text.{decodeUtf8,encodeUtf8}

src/Blob.mo
=> Add Blob.{to,From}Array{,Mut}

src/HashMap.mo, test/hashMapTest.mo
=> Fix divide-by-zero when removing from empty HashMap

src/Array.mo, test/arrayTest.mo
I said I was going to do this a long time ago... Sorry for the delay.
I copied the implementation from "Algorithms 4th Edition - Robert Sedgewick & Kevin Wayne"
=> Adds a merge-sort for Arrays

.github/workflows/ci.yml, .github/workflows/package-set.yml, src/Blob.mo, src/Bool.mo, src/Char.mo, src/Error.mo, src/Float.mo, src/Int.mo, src/Int16.mo, src/Int32.mo, src/Int64.mo, src/Int8.mo, src/Nat.mo, src/Nat16.mo, src/Nat32.mo, src/Nat64.mo, src/Nat8.mo, src/None.mo, src/Principal.mo, src/Text.mo
- merge next-moc into master
- update compiler binaries to latest 0.6.2 release
=> Claudio/update moc 0.6.2

src/Blob.mo
=> Update Blob.mo comment: bytes() is no more

src/HashMap.mo, src/TrieMap.mo, test/hashMapTest.mo, test/trieMapTest.mo
=> Feature: include keys and vals methods in TrieMap, HashMap.

src/Array.mo
reported at https://forum.dfinity.org/t/developer-documentation-feedback-survey/6440/2?u=nomeata
=> Docs typo: immutable, not mutable

src/Trie.mo, src/TrieMap.mo
Antora doesn't like the level 0 heading in these files. Let's nuke em
=> remove level 0 headings that Antora doesn't like

src/Array.mo
=> Deprecate Array.append

.github/workflows/ci.yml
- bump `nixos` channel
- bump `install-nix-action`
=> Renovate CI a bit

src/Array.mo, test/arrayTest.mo
I provided this implementation as the answer to a post in the developer forum,
and figured it should be part of the base package.
https://forum.dfinity.org/t/reversing-an-array/12724/3?u=paulyoung
=> Add Array.reverse

src/Trie.mo
These fell through the cracks. Follows up the #370. Pointed out by @crusso there.
=> Tweaks to `Trie.mo`

.github/CODEOWNERS~
Delete rogue emacs backup file
=> bugfix: delete CODEOWNERS~

src/Text.mo, test/textTest.mo
Finishes https://github.com/dfinity/motoko/issues/3150.
=> Optimise `Text.compare`

src/Trie.mo
Inspired by discussion by @crusso and @chenyan-dfinity in https://github.com/dfinity/motoko-base/pull/385
=> Trie: remove old, unused code.

src/Iter.mo, test/iterTest.mo
=> Add `Iter.sort`, and unit test.

src/Array.mo, src/Buffer.mo
First rewriting the already existing functionality, before adding extensions in another PR.
--------
In next PR:
Update unit tests
Unify variable naming and type parameters with new Buffer class
Extend module by adding more functions
=> Array functions extensions

test/TrieExampleTest.mo
Show how to invoke the `isValid` test on the `Trie`, to ensure it's structurally sound.
=> use `isValid` in unit test

.github/workflows/prettier.yml, test/trieMapTest.mo
Fixes what appears to be a GHA brownout which started breaking the new CI on Thursday:
=> chore: update matrix strategy in formatter CI

src/Error.mo, test/errorTest.mo, test/trieMapTest.mo
Improve `Error.mo` (very simple):
* Documentation
* Unit tests
Issue detected while writing unit test:
* https://github.com/dfinity/motoko/issues/3656
=> Error documentation and unit tests

src/List.mo, test/listTest.mo
Could use a few more for evaluation order and short-circuiting  but I expect this is all I'll get done before Xmas.
=> test: List module

src/Int.mo, test/intTest.mo, test/trieMapTest.mo
Improve `Int.mo`:
* Documentation
* Unit tests
Possible improvement for `Int.mo`:
* Fix typo in function name `neq`. https://github.com/dfinity/motoko-base/issues/456
=> Int documentation and unit tests

src/Int.mo, test/intTest.mo, test/trieMapTest.mo
Should be `neg()` for negate().
Reported in https://github.com/dfinity/motoko-base/issues/456
=> Fix typo in Int.neg() function name

src/RBTree.mo, test/RBTreeTest.mo
Improve `RBTree.mo`:
* Documentation
* Unit tests
Possible improvements for `RBTree` (https://github.com/dfinity/motoko-base/issues/492):
* Reduce garbage creation, especially during reading functions, such as `get()` and iteration.
* More efficient `size()` function.
=> RBTree documentation and unit tests

src/Random.mo
Adds an example for each public `Random` function and `Random.Finite` method.
Possible improvements: https://github.com/dfinity/motoko-base/issues/483
=> doc: Random module

doc/make_docs.sh, src/TrieSet.mo, test/trieSetTest.mo
* Fix for #446 (TrieSet.equal)
* Add isEmpty
* Add isSubset
* Optimize TrieSet.size (exploiting Trie.size())
* Test existing and new operations on larger example.
(still missing: iter, make/singleton, examples, better doc)
=> feat: fix TrieSet.equals, add TrieSet.isEmpty, TrieSet.isSubset; add tests

src/Float.mo, src/Random.mo, test/randomTest.mo
Fixes issue #492 and adds some very/too basic tests.
TODO:
=> bugfix: fix issue #492 plus some testing of Random.mo

src/Buffer.mo, src/List.mo
Adds one example to all list functions.
I wasn't sure whether to include type arguments or omit. For now, I've included them.
=> List examples

src/Int.mo, src/Nat.mo
In symmetry to the `Nat` documentation.
=> Refine Int documentation

src/List.mo
=> doc: correct some bounds on list ops

.github/workflows/ci.yml
to fix CI (:crossed_fingers:)
@ggreif, does one need to update the nix-channel too, whatever that is?
=> chore: bump install-nix-action from v16 to v20

src/Blob.mo
see https://github.com/dfinity/motoko/pull/4009
=> Blob.compare: Use new blob comparison prim

src/Text.mo, test/Text.test.mo
(tested locally against https://github.com/dfinity/motoko/pull/4216)
=> feat: add `Text.toLowercase`, `Text.toUppercase` with tests and doc

src/ExperimentalCycles.mo, src/Nat.mo, src/Timer.mo, test/Nat.test.mo
=> feat: scoped `setTimer`, etc.

CHANGELOG.md
Am I missing something important?
=> chore: add a pair of releases to `CHANGELOG.md`

package-lock.json, package.json, src/Array.mo, src/Principal.mo, test/js/importAll.js
=> fix: un-deprecate array append + CI sanity check

src/Float.mo
Port suggested changes from edits to generated files in https://github.com/dfinity/motoko/pull/4489
=> doc: update `Float.mo` documentation

src/Region.mo
Add a bit more description and discussion of memory management to `Region.mo`.
=> doc: update `Region.mo`

src/ExperimentalInternetComputer.mo
see comments in https://github.com/dfinity/motoko/pull/4618
=> Fix link in `ExperimentalInternetComputer.mo`

.github/CODEOWNERS, CHANGELOG.md
=> chore: amend the 0.14.3 changelog

CHANGELOG.md
=> chore: fix release blurb

package-lock.json, package.json
Includes https://github.com/ZenVoich/mops/pull/277.
=> Update Mops CLI to 1.5.1

src/Array.mo
This improves the performance of `Array.tabulateVar` and `Array.thaw`
=> feat: uses the new Array_tabulateVar primitive

test/OrderedMap.prop.test.mo
=> chore: eliminate warnings in property tests
