dfinity/motoko-base

src/Array.mo
src/Buffer.mo
src/Iter.mo
test/bufTest.mo

I think there's no need to abbreviate here, and given that we've also changed `Ord` to `Order` this seems like the right thing to do.

Renames `Buf` to `Buffer`

---

.github/workflows/ci.yml

Looks like I'll need someone with the right permissions to activate GH pages for this repo. And I'll probably also need to create a detached `gh-pages` branch. Opening anyway just to see what happens.

Push built documentation to GH pages

---

src/TrieMap.mo

I followed @kritzcreek's example in HashMap.
One question for the hyperlinks: What happens when we produce non-html output?
The current links seem brittle and likely to break, right? (or link to the wrong kind of document when we generate non-html output?)

Docs for TrieMap module

---

src/Trie.mo

Revises all method/function comments to comply with mo-doc format.
@kritzcreek Unresolved issue with `mo-doc` --- I found that mo-doc (from SDK 0.5.11) doesn't place internal (public) modules into the html output.  So, the `Build` module has doc comments, but they do not show up.

Document more of Trie module; clean up.

---

src/AssocList.mo

- Better summary line for the module (better conforms to the rest of the base package).
- Adds missing comments for some functions.
- "key-value pairs" ~> "entries" (to use style guide language more closely)

Finish documentation for AssocList module

---

src/Stack.mo

Tripped over this when running `vessel verify`. Think it would be worth trying to catch this one in CI?

Don't use a package import to reference ourself

---

doc/design.md
src/Array.mo
test/arrayTest.mo

Also documents `mapFilter` as the chosen name for type changing filters.
Fixes #191 
This is a breaking change, do we write that down somewhere? Maybe in the `motoko` repo changelog?

Array.filterMap -> Array.mapFilter

---

src/Array.mo
src/List.mo
src/Result.mo
test/arrayTest.mo
test/listTest.mo
test/package-set.dhall
test/resultTest.mo

We didn't have any names for `traverse` equivalents in the design document, so I just went with `traverseArray` and `traverseList`, but if you've got better names I'm happy to change those.
I removed the trapping functions, that shouldn't be here.

Various Result improvements

---

.github/workflows/ci.yml
src/Trie.mo
test/RBTreeTest.mo
test/arrayTest.mo
test/bufTest.mo
test/dequeTest.mo
test/floatTest.mo
test/funcTest.mo
test/heapTest.mo
test/intTest.mo
test/iterTest.mo
test/listTest.mo
test/natTest.mo
test/noneTest.mo
test/optionTest.mo
test/orderTest.mo
test/package-set.dhall
test/resultTest.mo
test/stackTest.mo
test/textTest.mo

Many of tests were warning about deprecated block syntax. This PR fixes that.

upgrade matchers, motoko release and use do blocks in tests

---

src/AssocList.mo
src/Buffer.mo
src/HashMap.mo
src/Iter.mo
src/Option.mo
src/Text.mo
src/Trie.mo
src/TrieMap.mo

These don't work in the Asciidoc output, and most of these are covered by the new `mo-doc` cross-referencing anyways.
Fixes #215

Removes Html links from the doc strings

---

src/Char.mo
src/Hash.mo
src/Int16.mo
src/Int32.mo
src/Int64.mo
src/Int8.mo
src/Nat16.mo
src/Nat32.mo
src/Nat64.mo
src/Nat8.mo
src/Random.mo
src/Word16.mo
src/Word32.mo
src/Word64.mo
src/Word8.mo
test/Makefile
test/charTest.mo
test/int8Test.mo
test/textTest.mo

this goes along with https://github.com/dfinity/motoko/pull/2326
(and should not be merged before). It adds new bit operations, wrapping
arithmetic and conversions to IntN and NatN.
It does not port the rest of base to avoid Word. See #214 for that (and
we will likely pull that in selectively).

Expose new bit operations on NatN and IntN

---

src/Char.mo
src/Word32.mo
test/charTest.mo

because of the upcoming deprecation of word types, we need to readicate
`Word` from all other modules’ interfaces.
This uses deprecation annotations to warn about the methods in `Char`
thta we will have to remove when we start warning about the `Word` type
itself.
This can be merged into `master` already, as support for the
`@deprecated` annotation is backward-compatible.

Deprecate Char.to/fromWord32

---

src/Text.mo
test/textTest.mo

Text.replace and other Text functions now use new CharBuffer implementation that properly supports multiple calls to pushBack.
Fixes  #234.

[Bug Fix] Text.replace and similar functions

---

src/Blob.mo
src/Hash.mo
src/HashMap.mo
src/Int.mo
src/Random.mo
src/Text.mo
src/Trie.mo
test/textTest.mo
test/trieSetTest.mo

slightly breaking, if someone else hooks into the representation of
Hash.
This makes `motoko-base` essentially free of `WordN` uses:
```
~/dfinity/motoko-base/src $ git grep Word|grep -v ^Word
Char.mo:  public let toWord32 : (c : Char) -> Word32 = Prim.charToWord32;
Char.mo:  public let fromWord32 : (w : Word32) -> Char = Prim.word32ToChar;
```
Requires https://github.com/dfinity/motoko/pull/2326

Hash: Switch from Word32 to Nat32

---

src/Text.mo

According to https://softwareengineering.stackexchange.com/a/145633 `djb2` does reasonably well, certainly a _lot_ better than what we have now.
Is this a breaking change? People might have stored these hashes in stable memory. Do we need to add a disclaimer that people shouldn't do that, or are we doomed to never improve our hash functions in base?

Uses a better hash function for Text

---

test/arrayTest.mo
test/resultTest.mo

explicates missing type instantiations that are now considered underconstrained by upcoming release of motoko

Changes to support variance based inference

---

src/Text.mo
test/textTest.mo

Fix: Make Text.compareWith use cmp argument, not Char.compare

---

src/List.mo
test/listTest.mo

Fixes #264 and makes replicate and tabulate stack safe too.
Adds very basic testing of above.

avoid stack overflow in append, replicate and tabulate

---

src/List.mo
src/Option.mo
src/Trie.mo

Updates `base` to not use deprecated `unwrap`, linked to #274

Fix unwraps

---

src/AssocList.mo
test/trieSetTest.mo

This PR fixes a logic bug in `AssocList.diff` (swapped cases).
This PR also adds a regression test that demonstrates the bug (thanks to @FloorLamp for the initial test and report; apologies for the extremely long delay in filing this officially and fixing it!).

Fix: AssocList diff bug fix; fixes Trie modules

---

.github/workflows/ci.yml
.github/workflows/package-set.yml
src/Float.mo

Use primitives provided by compiler for `Float` ⇔ `Int` conversions

---

src/StableMemory.mo

The StableMemory API for (almost) raw access to IC stable memory.
Still assumes 32-bit IC stable memory API (offsets are 32-bit)

[feat] StableMemory library

---

src/TrieMap.mo
test/trieMapTest.mo

In the current implementation the `size` gets reduced if the previous (removed) value is `null`.
https://github.com/dfinity/motoko-base/blob/2ac0707502bf7ffd816a37d480861f7a60e65628/src/TrieMap.mo#L63-L68
This results in an `arithmetic overflow`, since you'll be lowering `size` for every unknown key you try to remove.
I.e. if the map is empty and you remove an (unknown) key.
---
```
let a = H.TrieMap<Text, Nat>(Text.equal, Text.hash);
ignore a.remove("apple");
```

Fix arithmetic overflow in TrieMap.

---

src/ExperimentalStableMemory.mo

* Rename as Experimental
* Add warning to doc
* Extend doc
You can tell this project has too many Germans on it by the length of the library names.

ExperimentalStableMemory 

---

src/ExperimentalStableMemory.mo

Upgrade ExperimentalStableMemory.mo to 64-bit.
This is a breaking change, but to an experimental library, so we can live with that.

make StableMemory 64-bit

---

src/ExperimentalStableMemory.mo

- fix 0xFFFF_FFFF (should be 0xFFFF_FFFF_FFFF_FFFF)
- documents --max-stable-pages interaction.

feat: ExperimentalStableMemory: document  --max-stable-pages

---

src/Principal.mo

This will hopefully be much cheaper in cycles and allocation.

Use static literal `Blob` in `isAnonymous`

---

test/Makefile

As per https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md#0310, the `light beam` backend has been removed from `Wasmtime`, thus the backend isn't switchable any more. The `--cranelift` option is gone now, accordingly.

Fix wasmtime run for error `'--disable-cache' which wasn't expected`

---

src/RBTree.mo
test/RBTreeTest.mo

Right now, it doesn't work when you `remove` or `delete` elements from the `RBTree`, since those methods just set the value of a `#node` to `null`. The fix is to treat the tree as empty in the latter case.

Correctly compute RBTree size

---

src/Iter.mo
test/iterTest.mo

Add `Iter.filter` method and simplify `Iter.map` implementation

---

src/Iter.mo
src/List.mo
test/listTest.mo

In this PR, I have added a method `toIter` to `List.mo` to convert `List` to `Iter`.
The first reason for this addition is that it is intuitive to have the conversion method defined in the class/module from which it is converted, in association with for example Rust's `array.into_iter()`.
The second reason is that the current library requires the conversion from `List` to `Iter` using `Iter.fromList()`, so there are situations where an extra `import Iter "mo:base/Iter";` is needed just for the conversion.
Thank you for your consideration.

Add `toIter` method to `List`

---

src/Trie.mo

Arguably this makes the code more readable. The type inference for call-site type parameters has been strengthened considerably, so almost all type parameter passing can be eliminated from `Trie.mo`.

Let type inference determine the type parameters if possible

---

src/Hash.mo
src/Int.mo

Fixes #376 
- copies now deprecated Hash.hashNat8 into Int.mo (to suppress deprecation of Hash.hashNat8)
- deprecates dodgy hashing functions Int.mo.
Just a band-aid to prevent users getting deprecation warnings they cannot fix themselves.

bugfix: avoid Hash.hashNat8 deprecation when importing Int.mo

---

src/ExperimentalStableMemory.mo

Expose `ExperimentalStableMemory.stableVarQuery` for estimating stable variable storage requirements during upgrade
```
ExperimentalStableMemory.stableVarQuery : () -> (shared query () -> async {size : Nat64})
```
Returns a query that, when called, returns the number of bytes of (real) IC stable memory that would be occupied by persisting its current stable variables before an upgrade.
This function may be used to monitor or limit real stable memory usage.
The query computes the estimate by running the first half of an upgrade, including any `preupgrade` system method.
Like any other query, its state changes are discarded so no actual upgrade (or other state change) takes place.
The query can only be called by the enclosing actor and will trap for other callers.

feat: implement `ExperimentalStableMemory.stableVarQuery` for estimating stable variable storage requirements during upgrade

---

src/ExperimentalInternetComputer.mo

Implement  basic `ExperimentalInternetComputer.countInstructions(comp)`, hiding the limitations of IC performance counters (reset  to 0 after each entrypoint, invariant within blocks) by restricting measurements to local, synchronous computations.
cf. https://github.com/dfinity/motoko/issues/3294

feat: implement `ExperimentalInternetComputer.countInstructions(comp)`

---

src/Array.mo
test/arrayTest.mo

Creates a buffer from an array.

Transform an array into a buffer via `Array.buffer`.

---

.gitignore
src/Array.mo
src/Buffer.mo
src/Hash.mo
src/Iter.mo
test/arrayTest.mo
test/bufTest.mo

Base Library Extension Doc: https://docs.google.com/document/d/1uKouujLL3KueLpqjjFV2gd4dqu_6GYD107WBb6_GSVE/edit
This last point is related to the RRB Trees, Rope, and Finger Trees data structures that I was discussing before. For various reasons, I am leaning towards an RRB Tree implementation of a scalable sequence structure, if it is necessary. See a talk on this data structure here: https://www.youtube.com/watch?v=sPhpelUfu8Q

Buffer Class Extension

---

src/Buffer.mo

Added examples to the class method documentations.
And ran new Motoko formatter over Buffer file.

Add Examples for class methods in Buffer

---

src/Trie.mo
test/testLenClamp.mo

@nomeata suggests:
> I wonder if one shouldn't simply change the code to allow arbitrary sized association lists in the 32th level of the tree. The bitpos is readily available, so it should be easy to not split the list at that level. Then the tree would not have the problem of at most 8 collisions at all
That would also let us remove the trap in `Hash.mo` (when we run out of bits).

bugfix: `Trie.mo`: fix off-by-one error in `lenClamp`; restore original invariant

---

.github/workflows/prettier.yml

Fixes what appears to be a GHA brownout which started breaking the new CI on Thursday:

chore: update matrix strategy in formatter CI

---

src/Timer.mo

Adds the public API to support the default timer mechanism
- `setTimer : (Duration, () -> async ()) -> TimerId` to insert a one-off timer
- `recurringTimer : (Duration, () -> async ()) -> TimerId ` to insert a repeating timer
- `cancelTimer : TimerId -> ()` to remove timer
where `Duration` is a variant that can specify a timespan in seconds or nanoseconds.
Please refer to the PR https://github.com/dfinity/motoko/pull/3542 for the gory details.
Some caveats:
- importing `Timer.mo` will fail when invoked as `moc -no-timer`
- these functions have no effect (other than filling the heap) when the user chooses to implement `system func timer` herself (i.e. opting out of the Motoko default timer mechanism).
- `Duration` should be well above the round time to make this mechanism more efficient …

feat: user-facing API for timers

---

src/Array.mo

This aims to address https://forum.dfinity.org/t/how-to-get-a-array-lengh/8346 and other instances of people asking about how to get the size of an array due to it being omitted from the generated documentation.

Add `Array.size`

---

.github/workflows/ci.yml
.prettierrc
package-lock.json
package.json
src/Trie.mo
test/js/checkReferences.js
test/js/index.js

Fixes a reference to `"mo:base/Debug"` in `Trie.mo` (originating from a PR in November), which appears to break `vessel verify` as mentioned in [this forum topic](https://forum.dfinity.org/t/heartbeat-improvements-timers-community-consideration/14201/94) and indicated by [this PR's CI output](https://github.com/dfinity/vessel-package-set/actions/runs/3797230768/jobs/6457979836). 
This also appears to affect `moc 0.7.4`, so we should definitely find a way to automatically screen for future regressions like this.

fix: non-local import in `Trie.mo`

---

src/CertifiedData.mo

Adds examples for CertifiedData. The examples aren't interactive since they require a canister environment, but they seem useful to use as copy/paste examples.

chore: add examples for CertifiedData

---

src/ExperimentalStableMemory.mo

Adds an example for each `ExperimentalStableMemory` function.
Possible improvements: https://github.com/dfinity/motoko-base/issues/481

doc: ExperimentalStableMemory module

---

src/Int16.mo
src/Int32.mo
src/Int64.mo
src/Int8.mo
test/int16Test.mo
test/int32Test.mo
test/int64Test.mo
test/int8Test.mo

Fix some most obvious issues reported in https://github.com/dfinity/motoko-base/issues/476:
* Offer minimum and maximum integer constants
* Remove superfluous second argument in `bitnot()`

Fix: Base library issues in Int8/16/32/64

---

src/ExperimentalCycles.mo

Extend documentation for `ExperimentalCycles.mo`.
No unit tests as the functionality requires actors/async that is not available in the base library unit tests (as far as I know).

ExperimentalCycles documentation (no unit tests)

---

test/RBTreeTestMore.mo

Currently, the CI builds for the incremental GC (https://github.com/dfinity/motoko/pull/3756) fail because they run out of memory for this test case (where memory is not collected). The incremental GC has a somewhat higher memory footprint as it uses larger object headers, with an additional forwarding pointer.
Therefore, reducing the test size a little bit to also fit for the future incremental GC.

test: reduce test size to fit incremental GC

---

src/AssocList.mo

* Fixes #530 (apart from using tail-recursion)
* Optimize `find` to avoid inner closure allocation
* Remove very old profiling labels
https://m7sm4-2iaaa-aaaab-qabra-cai.ic0.app/?tag=47089978 shows huge (ca. 33%) reduction in allocation and cycles.
```
› testNew()
("{heap_diff = 16_080_000; instructions = 92_841_876}")
› testOld()
("{heap_diff = 24_076_000; instructions = 125_287_686}")
```
code:
```
import AssocList = "mo:base/AssocList";
import List = "mo:base/List";
import Nat = "mo:base/Nat";
import IC = "mo:base/ExperimentalInternetComputer";
import Prim = "mo:prim";
actor {
type AssocList<K, V> = AssocList.AssocList<K, V>;
func replace<K, V>(
map : AssocList<K, V>,
key : K,
equal : (K, K) -> Bool,
value : ?V
) : (AssocList<K, V>, ?V) {
var prev : ?V = null;
func rec(al : …
```

optimize AssocList.replace

---

src/AssocList.mo
test/Makefile
test/assocListTest.mo
test/trieMapTest.mo
test/trieSetTest.mo
test/trieTest.mo

Optimize AssocList.replace to:
* avoid reconstructing list on deletion of absent association, avoiding 0(n) allocations.
* insert association for new key at front (not end) of list on insertion, avoiding 0(n) allocations.
The trick is to use the `prev` value, set by recursive calls, to determine whether to to re-use or re-build the original assoc list.
TODO: factor our nested ins/del functions into top-level functions for easier review.
Caveat: This changes the concrete order of entries for Trie and probably HashMap, so breaks our tests and any other user code that relies on the ordering of entries.
https://m7sm4-2iaaa-aaaab-qabra-cai.ic0.app/?tag=1498380597
```
› testOld()
("{heap_diff = 24_076_000; instructions = 125_295_036}")
› testNew()
("{heap_diff = 16_080_000; instructions = …
```

perf: optimize AssocList.replace to avoid unnecesary allocation

---

.github/workflows/ci.yml
package-lock.json
package.json

Fixes #561, which was apparently caused by a bug that was fixed a while ago in the `mo-test` command. 
The original error was fixed in https://github.com/dfinity/motoko-dev-server/pull/25, which was a regression from moving the unit test logic from the VS Code extension into the `mo-dev` codebase.

Bump `mo-dev`

---

src/Trie.mo

Mostly removing redundant parentheses.

chore: cleanup `Trie.mo`

---

src/Array.mo
src/Text.mo
test/Array.test.mo
test/Iter.test.mo
test/Text.test.mo

This change introduces new utility functions to deal with arrays:
* Array.slice
* Array.indexOf, Array.lastIndexOf
* Array.nextIndexOf, Array.prevIndexOf
* Text.toArray, Text.toVarArray
Controversial design choices:
* `Array.slice` accepts a half-closed range `[from, to)`. The goal is to eliminate the need to subtract one from the array size and make off-by-one errors less likely. Both `Array.slice(a, 0, a.size())` and `Array.slice(a, 0, 0)` work as expected. I found this approach much more convenient in practice than inclusive ranges that `Iter.range(from, to)` generates.
* `Array.nextIndexOf` and `Array.prevIndexOf` are assymetrical. The starting position in `nextIndexOf` is inclusive, while the starting position in `prevIndexOf` is exclusive. The goal is again to eliminate the need to …

feat: more array utility functions

---

src/Int.mo
src/Int16.mo
src/Int32.mo
src/Int64.mo
src/Int8.mo
src/Nat16.mo
src/Nat32.mo
src/Nat64.mo
src/Nat8.mo

Expose these: https://github.com/dfinity/motoko/pull/4139
Converting to adjacent fix-width types for:
- `Int8`
- `Int16`
- `Int32`
- `Int64`
- `Nat8`
- `Nat16`
- `Nat32`
- `Nat64`
And fleshing out the documentation for these modules to be up to standard with the `Nat` and `Int` modules.

Add bindings for adjacent fix-width numerical conversions and flesh out docs

---

src/ExperimentalStableMemory.mo
src/Region.mo

Note this is intended for branch next-moc.
CI expected to fail for base branch next-moc.
Builds fine against moc regions branch
Replaces original PR #516 (that I forgot existed but also targeted master, not next-moc as required)
Byte-level access to isolated, (virtual) stable memory _regions_.
This is a moderately lightweight abstraction over IC _stable memory_ and supports persisting
regions of binary data across Motoko upgrades.
Use of this module is fully compatible with Motoko's use of
_stable variables_, whose persistence mechanism also uses (real) IC stable memory internally, but does not interfere with this API.
It is also fully compatible with existing uses of the `ExperimentalStableMemory` library, which has a similar interface, but,
only supported a single memory region, without …

feat: `Region.mo` library offering isolated regions of IC stable memory

---

src/Array.mo

Reported in https://forum.dfinity.org/t/bug-in-array-tabulatevar/24424

fix tabulateVar

---

test/Makefile

moc > 0.10.1 produced binares require additional flags to run on wasmtime, due their use of mutli-memory and bulk-memory instructions to emulate IC stable memory (and Motoko regions).
c.f. https://github.com/dfinity/motoko/pull/4256/

enable multi-memory, bulk-memory on wasmtime

---

src/ExperimentalInternetComputer.mo

Returns the current value of IC _performance counter_ `counter`:
* Counter `0` is the _current execution instruction counter_, counting instructions only since the beginning of the current IC message.
This counter is reset to value `0` on shared function entry and every `await`.
It is therefore only suitable for measuring the cost of synchronous code.
* Counter '1' is the call context instruction counter for the current call context.
For replicated message executing, this excludes the cost of nested IC calls (even to the current canister).
For non-replicated messages, such as composite queries, it includes the cost of nested calls.
The current value of this counter is preserved across `awaits` (unlike counter `0`).
* The function (currently) traps if `counter` >= 2.
Consult [Performance …

feat: define ExperimentalInternetComputer.performanceCounter : Nat32 -> Nat64;

---

src/Blob.mo

There is a rendering issue on https://mops.one/base/docs/Blob due to this extra space.

Remove extra space from doc comment in `Blob.mo`

---

doc/design.md

This pull request addresses several typographical errors in the Motoko Base Library's design documentation. Ensuring accuracy and clarity in our documentation is vital for effective communication among developers and for maintaining the high standard of our project.
- Corrected 'encapsultion' to 'encapsulation' in the Classes section. This change clarifies the intended meaning, emphasizing the importance of encapsulation in abstract data types.
- Updated 'valus' to 'values' in the Containers section under the description of the `keys` iterator. This fix ensures that the documentation accurately represents the functionality of the iterator.
- Fixed 'distinghuish' to 'distinguish' in the Containers section. This modification aids in presenting a clearer rationale for the choice of the `put` …

Documentation Typo Fixes for Motoko Base Library Design Guide

---

src/Option.mo
test/Option.test.mo

@crusso 
I use this all the time when writing Matchers tests that require equality checking. Would be nice to have in base 🙂

add Option.equal

---

src/List.mo

doc: update `List.mo`

---

src/Result.mo

Low hanging solution for https://dx.internetcomputer.org/topic/166
I found myself using this a fair amount when integrating with the new Cycles Ledger, and see it in a fair number of places that integrate with protocol canisters that were built in Rust.

feat: add Result.toUpper/Result.fromUpper to facilitate interop with common IC canisters using upppercased result variants.

---

src/Trie.mo
src/TrieMap.mo
src/TrieSet.mo

Clarify the limits and claims
The claim about trie representation being canonical does not hold if the hash has collisions and requires non-singleton assoc lists at the leaves. I'm also not sure it's preserved by deletion.

doc: document Trie/TrieSet/TrieMap collision limits

---

src/AssocList.mo
src/Deque.mo
src/List.mo
src/RBTree.mo
src/Stack.mo
src/Text.mo
src/TrieSet.mo
test/Option.test.mo

Refactor base library to avoid warnings of the improved unused declaration detection, see bug fix https://github.com/dfinity/motoko/pull/4560 for https://github.com/dfinity/motoko/issues/4508.

Code Refactoring: Curate More Unused Declarations

---

src/Iter.mo

this PR adds `Iter.concat` utility function, which concatenates two iterables.
Additionally fixed compilation warning on unused variable and a typo in doc string

Add Iter.concat function

---

src/Debug.mo

to mention canister logs
fixes issue #673

doc: update doc on Debug.print

---

src/Timer.mo

... other than submitting the self-call, of course

doc: add notes that timer jobs should be side-effect-free

---

src/Timer.mo

Adjusts the wording of the `Timer` documentation based on feedback. This is intended as a starting point; please feel free to suggest additional changes.

Update `Timer` doc comments

---

src/Error.mo

... it will be returned in the future

chore: mention `#system_unknown`

---

CHANGELOG.md
src/Error.mo

This predicate categorises `Error`s based on the potential success when resending the message. It _doesn't_ consider semantic issues like idempotence or such.

feat: add `Error.isRetryPossible`, a predicate for non-fatal messaging errors

---

CHANGELOG.md
src/ExperimentalInternetComputer.mo

(backported API fix from `new-base` 0.2.0)
This is a mildly breaking change, as the feature is not fully on the subnets yet.

feat: make `replyDeadline` an optional return type
